-------------------------------------------------------------------------------
Test set: es.upm.grise.profundizacion.td3.FileAlarmTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.733 s <<< FAILURE! -- in es.upm.grise.profundizacion.td3.FileAlarmTest
es.upm.grise.profundizacion.td3.FileAlarmTest.testDatabaseError -- Time elapsed: 0.014 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected es.upm.grise.profundizacion.td3.DatabaseProblemException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3111)
	at es.upm.grise.profundizacion.td3.FileAlarmTest.testDatabaseError(FileAlarmTest.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

